image: debian/testing
packages:
  - emacs
sources:
  - https://git.sr.ht/~thanosapollo/yeetube.el
tasks:
  - run-tests: |
      cd yeetube.el/test
      emacs -q -batch -l yeetube-tests.el
triggers:
  - action: email
    condition: failure
    to: ~thanosapollo/yeetube-tests@lists.sr.ht
